/* 
 * Telemost API v1
 *
 * API to create and manage video meetings and live streams in Yandex.Telemost
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Y360OutlookConnector.Clients.Telemost.Model
{
    /// <summary>
    /// Short representation of conference
    /// </summary>
    [DataContract]
    public class ConferenceShort
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConferenceShort" /> class.
        /// </summary>
        /// <param name="id">Identifier of conference.</param>
        /// <param name="joinUrl">Link for participants to join conference.</param>
        /// <param name="liveStream">liveStream.</param>
        public ConferenceShort(string id = null, string joinUrl = null, ConferenceShortLiveStream liveStream = null)
        {
            Id = id;
            JoinUrl = joinUrl;
            LiveStream = liveStream;
        }

        /// <summary>
        /// Identifier of conference
        /// </summary>
        /// <value>Identifier of conference</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Link for participants to join conference
        /// </summary>
        /// <value>Link for participants to join conference</value>
        [DataMember(Name = "join_url", EmitDefaultValue = false)]
        public string JoinUrl { get; set; }

        /// <summary>
        /// Gets or Sets LiveStream
        /// </summary>
        [DataMember(Name = "live_stream", EmitDefaultValue = false)]
        public ConferenceShortLiveStream LiveStream { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConferenceShort {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  JoinUrl: ").Append(JoinUrl).Append("\n");
            sb.Append("  LiveStream: ").Append(LiveStream).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }        
    }
}
