/* 
 * Telemost API v1
 *
 * API to create and manage video meetings and live streams in Yandex.Telemost
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Y360OutlookConnector.Clients.Telemost.Model
{
    /// <summary>
    /// Live stream data. Missing when conference has no live stream
    /// </summary>
    [DataContract]
    public class ConferenceShortLiveStream
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConferenceShortLiveStream" /> class.
        /// </summary>
        /// <param name="watchUrl">Link for viewers to watch stream.</param>
        public ConferenceShortLiveStream(string watchUrl = default(string))
        {
            this.WatchUrl = watchUrl;
        }
        
        /// <summary>
        /// Link for viewers to watch stream
        /// </summary>
        /// <value>Link for viewers to watch stream</value>
        [DataMember(Name="watch_url", EmitDefaultValue=false)]
        public string WatchUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConferenceShortLiveStream {\n");
            sb.Append("  WatchUrl: ").Append(WatchUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }        
    }
}
