//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Y360OutlookConnector.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Y360OutlookConnector.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string AboutWindow_CopyrightText {
            get {
                return ResourceManager.GetString("AboutWindow_CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string AboutWindow_LicenseAgreement {
            get {
                return ResourceManager.GetString("AboutWindow_LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string AboutWindow_NewVersionString {
            get {
                return ResourceManager.GetString("AboutWindow_NewVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string AboutWindow_UpdateNowButton {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string AboutWindow_VersionString {
            get {
                return ResourceManager.GetString("AboutWindow_VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string AboutWindow_WindowTitle {
            get {
                return ResourceManager.GetString("AboutWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string AutoUpdateWindow_UpdateAvailableDescription {
            get {
                return ResourceManager.GetString("AutoUpdateWindow_UpdateAvailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string AutoUpdateWindow_UpdateAvailableMessage {
            get {
                return ResourceManager.GetString("AutoUpdateWindow_UpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string AutoUpdateWindow_UpdateButton {
            get {
                return ResourceManager.GetString("AutoUpdateWindow_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string AutoUpdateWindow_WindowTitle {
            get {
                return ResourceManager.GetString("AutoUpdateWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LoginWindow_AuthCodePageDesc {
            get {
                return ResourceManager.GetString("LoginWindow_AuthCodePageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LoginWindow_AuthCodePageFailure {
            get {
                return ResourceManager.GetString("LoginWindow_AuthCodePageFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LoginWindow_AuthCodePageTitle {
            get {
                return ResourceManager.GetString("LoginWindow_AuthCodePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LoginWindow_WindowTitle {
            get {
                return ResourceManager.GetString("LoginWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_LoginWebViewFailureDescription {
            get {
                return ResourceManager.GetString("Messages_LoginWebViewFailureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_LoginWebViewFailureOpenBrowser {
            get {
                return ResourceManager.GetString("Messages_LoginWebViewFailureOpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_LoginWebViewFailureTitle {
            get {
                return ResourceManager.GetString("Messages_LoginWebViewFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_LoginWebViewFailureTryAgain {
            get {
                return ResourceManager.GetString("Messages_LoginWebViewFailureTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_NoInternetMessageDesc {
            get {
                return ResourceManager.GetString("Messages_NoInternetMessageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_NoInternetMessageTitle {
            get {
                return ResourceManager.GetString("Messages_NoInternetMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_ProductDescription {
            get {
                return ResourceManager.GetString("Messages_ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_ProductName {
            get {
                return ResourceManager.GetString("Messages_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_ProxyErrorMessageButton {
            get {
                return ResourceManager.GetString("Messages_ProxyErrorMessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_ProxyErrorMessageDescription {
            get {
                return ResourceManager.GetString("Messages_ProxyErrorMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_ProxyErrorMessageTitle {
            get {
                return ResourceManager.GetString("Messages_ProxyErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_SyncFailureMessageDescription {
            get {
                return ResourceManager.GetString("Messages_SyncFailureMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_SyncFailureMessageTitle {
            get {
                return ResourceManager.GetString("Messages_SyncFailureMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_SyncProgressCalendars {
            get {
                return ResourceManager.GetString("Messages_SyncProgressCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_SyncProgressContacts {
            get {
                return ResourceManager.GetString("Messages_SyncProgressContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_SyncProgressTasks {
            get {
                return ResourceManager.GetString("Messages_SyncProgressTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_UnauthorizedMessageButton {
            get {
                return ResourceManager.GetString("Messages_UnauthorizedMessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Messages_UnauthorizedMessageDescription {
            get {
                return ResourceManager.GetString("Messages_UnauthorizedMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_ApplyButton {
            get {
                return ResourceManager.GetString("SettingsWindow_ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_CancelButton {
            get {
                return ResourceManager.GetString("SettingsWindow_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_GeneralSettingsPanelTitle {
            get {
                return ResourceManager.GetString("SettingsWindow_GeneralSettingsPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_IncludeDebugLevelInfo {
            get {
                return ResourceManager.GetString("SettingsWindow_IncludeDebugLevelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_LogClearLink {
            get {
                return ResourceManager.GetString("SettingsWindow_LogClearLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_LoginButton {
            get {
                return ResourceManager.GetString("SettingsWindow_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_LogoutButton {
            get {
                return ResourceManager.GetString("SettingsWindow_LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_LogPanelDescription {
            get {
                return ResourceManager.GetString("SettingsWindow_LogPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_LogPanelTitle {
            get {
                return ResourceManager.GetString("SettingsWindow_LogPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_LogShowLink {
            get {
                return ResourceManager.GetString("SettingsWindow_LogShowLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_LogShowWarning {
            get {
                return ResourceManager.GetString("SettingsWindow_LogShowWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_ProxyErrorLogin {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_ProxyErrorServer {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_ProxyManualSettings {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyManualSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_ProxyPanelDescription {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_ProxyPanelTitle {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_ProxyPassword {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_ProxyUrlErrorEmpty {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyUrlErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_ProxyUrlErrorInvalidValue {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyUrlErrorInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_ProxyUrlErrorNonHttp {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyUrlErrorNonHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_ProxyUrlLabel {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_ProxyUserName {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_UseExternalBrowserForLogin {
            get {
                return ResourceManager.GetString("SettingsWindow_UseExternalBrowserForLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_UserLogoutDesc {
            get {
                return ResourceManager.GetString("SettingsWindow_UserLogoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SettingsWindow_WindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_ApplyButton {
            get {
                return ResourceManager.GetString("SyncConfigWindow_ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_CalendarsFolderType {
            get {
                return ResourceManager.GetString("SyncConfigWindow_CalendarsFolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_CancelButton {
            get {
                return ResourceManager.GetString("SyncConfigWindow_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_ContactsDefaultName {
            get {
                return ResourceManager.GetString("SyncConfigWindow_ContactsDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_ContactsFolderType {
            get {
                return ResourceManager.GetString("SyncConfigWindow_ContactsFolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_ExternalContactsName {
            get {
                return ResourceManager.GetString("SyncConfigWindow_ExternalContactsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_FolderAlreadyUsedByCalendarMessage {
            get {
                return ResourceManager.GetString("SyncConfigWindow_FolderAlreadyUsedByCalendarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_FolderAlreadyUsedByContacsMessage {
            get {
                return ResourceManager.GetString("SyncConfigWindow_FolderAlreadyUsedByContacsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_FolderAlreadyUsedByTasksMessage {
            get {
                return ResourceManager.GetString("SyncConfigWindow_FolderAlreadyUsedByTasksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_FoldersColumnName {
            get {
                return ResourceManager.GetString("SyncConfigWindow_FoldersColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_PersonalContactsName {
            get {
                return ResourceManager.GetString("SyncConfigWindow_PersonalContactsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_PrimaryLabel {
            get {
                return ResourceManager.GetString("SyncConfigWindow_PrimaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_ProxySettingsLink {
            get {
                return ResourceManager.GetString("SyncConfigWindow_ProxySettingsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_ReadOnlyTooltip {
            get {
                return ResourceManager.GetString("SyncConfigWindow_ReadOnlyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_ServerColumnName {
            get {
                return ResourceManager.GetString("SyncConfigWindow_ServerColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_SharedContactsName {
            get {
                return ResourceManager.GetString("SyncConfigWindow_SharedContactsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_SyncFailureGeneralError {
            get {
                return ResourceManager.GetString("SyncConfigWindow_SyncFailureGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_SyncFailureProxyError {
            get {
                return ResourceManager.GetString("SyncConfigWindow_SyncFailureProxyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_SyncFailureServerError {
            get {
                return ResourceManager.GetString("SyncConfigWindow_SyncFailureServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_SyncSuccess {
            get {
                return ResourceManager.GetString("SyncConfigWindow_SyncSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_TasksFolderType {
            get {
                return ResourceManager.GetString("SyncConfigWindow_TasksFolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_WindowTitle {
            get {
                return ResourceManager.GetString("SyncConfigWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_WrongFolderTypeForCalendarMessage {
            get {
                return ResourceManager.GetString("SyncConfigWindow_WrongFolderTypeForCalendarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_WrongFolderTypeForContactsMessage {
            get {
                return ResourceManager.GetString("SyncConfigWindow_WrongFolderTypeForContactsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_WrongFolderTypeForTasksMessage {
            get {
                return ResourceManager.GetString("SyncConfigWindow_WrongFolderTypeForTasksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string SyncConfigWindow_СreatingFolderErrorMessage {
            get {
                return ResourceManager.GetString("SyncConfigWindow_СreatingFolderErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_AuthorizeInTelemostMessage {
            get {
                return ResourceManager.GetString("Telemost_Messages_AuthorizeInTelemostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_InfoPanelTitle {
            get {
                return ResourceManager.GetString("Telemost_Messages_InfoPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_MeetingCreatedMessage {
            get {
                return ResourceManager.GetString("Telemost_Messages_MeetingCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_MeetingCreateErrorMessage {
            get {
                return ResourceManager.GetString("Telemost_Messages_MeetingCreateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_MeetingCreateForbiddenErrorMessage {
            get {
                return ResourceManager.GetString("Telemost_Messages_MeetingCreateForbiddenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_MeetingCreatingMessage {
            get {
                return ResourceManager.GetString("Telemost_Messages_MeetingCreatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_MeetingInternalMessage {
            get {
                return ResourceManager.GetString("Telemost_Messages_MeetingInternalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_MeetingLinkMessage {
            get {
                return ResourceManager.GetString("Telemost_Messages_MeetingLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_MeetingSubject {
            get {
                return ResourceManager.GetString("Telemost_Messages_MeetingSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_MeetingUpdatedMessage {
            get {
                return ResourceManager.GetString("Telemost_Messages_MeetingUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_MeetingUpdateErrorMessage {
            get {
                return ResourceManager.GetString("Telemost_Messages_MeetingUpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_MeetingUpdateForbiddenErrorMessage {
            get {
                return ResourceManager.GetString("Telemost_Messages_MeetingUpdateForbiddenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_MeetingUpdatingMessage {
            get {
                return ResourceManager.GetString("Telemost_Messages_MeetingUpdatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Messages_NoInternetErrorMessage {
            get {
                return ResourceManager.GetString("Telemost_Messages_NoInternetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_SettingsWindow_CreateMeetingButtonText {
            get {
                return ResourceManager.GetString("Telemost_SettingsWindow_CreateMeetingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_SettingsWindow_ExternaUsersWontBeAbleToJoinLabelWarningText {
            get {
                return ResourceManager.GetString("Telemost_SettingsWindow_ExternaUsersWontBeAbleToJoinLabelWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_SettingsWindow_LoginButtonText {
            get {
                return ResourceManager.GetString("Telemost_SettingsWindow_LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_SettingsWindow_LoginLabelText {
            get {
                return ResourceManager.GetString("Telemost_SettingsWindow_LoginLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_SettingsWindow_OnlyEmployeesCheckBoxLabelText {
            get {
                return ResourceManager.GetString("Telemost_SettingsWindow_OnlyEmployeesCheckBoxLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_SettingsWindow_SaveSettingsButtonText {
            get {
                return ResourceManager.GetString("Telemost_SettingsWindow_SaveSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_SettingsWindow_SettingsWindowTitle {
            get {
                return ResourceManager.GetString("Telemost_SettingsWindow_SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_SettingsWindow_TelemostMeetingLabelText {
            get {
                return ResourceManager.GetString("Telemost_SettingsWindow_TelemostMeetingLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Toolbar_ExternalMeetingButton {
            get {
                return ResourceManager.GetString("Telemost_Toolbar_ExternalMeetingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Toolbar_InternalMeetingButton {
            get {
                return ResourceManager.GetString("Telemost_Toolbar_InternalMeetingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Toolbar_RibbonMenuButton {
            get {
                return ResourceManager.GetString("Telemost_Toolbar_RibbonMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Telemost_Toolbar_SettingsButton {
            get {
                return ResourceManager.GetString("Telemost_Toolbar_SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Toolbar_AboutButton {
            get {
                return ResourceManager.GetString("Toolbar_AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Toolbar_HelpButton {
            get {
                return ResourceManager.GetString("Toolbar_HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Toolbar_LoginButton {
            get {
                return ResourceManager.GetString("Toolbar_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Toolbar_RibbonGroup {
            get {
                return ResourceManager.GetString("Toolbar_RibbonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Toolbar_RibbonTab {
            get {
                return ResourceManager.GetString("Toolbar_RibbonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Toolbar_SettingsButton {
            get {
                return ResourceManager.GetString("Toolbar_SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Toolbar_SyncNowButton {
            get {
                return ResourceManager.GetString("Toolbar_SyncNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Toolbar_SyncNowButtonRunning {
            get {
                return ResourceManager.GetString("Toolbar_SyncNowButtonRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Toolbar_SyncTargetsButton {
            get {
                return ResourceManager.GetString("Toolbar_SyncTargetsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string YandexCalendar_Toolbar_EditEventButton {
            get {
                return ResourceManager.GetString("YandexCalendar_Toolbar_EditEventButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string YandexCalendar_Toolbar_NavigateToCalendarButton {
            get {
                return ResourceManager.GetString("YandexCalendar_Toolbar_NavigateToCalendarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string YandexCalendar_Toolbar_RibbonToolbarButton {
            get {
                return ResourceManager.GetString("YandexCalendar_Toolbar_RibbonToolbarButton", resourceCulture);
            }
        }
    }
}
